# Generated by Django 4.1.7 on 2023-02-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_id_in_thematic', models.IntegerField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.ManyToManyField(related_name='axis_episodes', to='biosignalsindex.axis')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id_in_session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThematicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id_in_thematic', models.IntegerField()),
                ('thematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.thematicunit')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_type', models.CharField(choices=[('GR', 'Graph'), ('RAW', 'Raw data')], max_length=3)),
                ('biosignal', models.CharField(choices=[('HR', 'Heart Rate'), ('SC', 'Skin Conductance'), ('TEMP', 'Temperature')], max_length=4)),
                ('path', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/RealityLab-Guest/Desktop/TT8/data'), recursive=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.episode')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.session'),
        ),
        migrations.AddField(
            model_name='episode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.session'),
        ),
        migrations.AddField(
            model_name='axis',
            name='thematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosignalsindex.thematicunit'),
        ),
    ]
