# Generated by Django 4.1.7 on 2023-07-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biopeakmetadata',
            options={'ordering': ['biometric__abbr', 'participant']},
        ),
    ]
