# Generated by Django 4.1.7 on 2023-03-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0002_rename_session_sociodramasession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociodramasession',
            name='thematic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='biosignalsindex.thematicunit'),
        ),
    ]
