# Generated by Django 4.1.7 on 2023-03-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0004_rename_description_axis_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmaterial',
            name='biosignal',
            field=models.CharField(choices=[('HR', 'Heart Rate'), ('SC', 'Skin Conductance'), ('TEMP', 'Temperature'), ('ALL', 'All')], max_length=4),
        ),
        migrations.AlterField(
            model_name='participantmaterial',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='biosignalsindex.episode'),
        ),
        migrations.AlterField(
            model_name='participantmaterial',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to='biosignalsindex.participant'),
        ),
        migrations.AlterField(
            model_name='participantmaterial',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
