# Generated by Django 4.1.7 on 2023-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0004_alter_scene_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedScenesInAxis',
        ),
    ]
