# Generated by Django 4.1.7 on 2023-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0005_delete_orderedscenesinaxis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sceneintaskmetadata',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='sceneintaskmetadata',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='scene',
            name='ending_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='starting_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ending_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='starting_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
