# Generated by Django 4.1.7 on 2023-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0006_rename_participant_id_in_session_participant_sensor_id_in_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmaterial',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
