# Generated by Django 4.1.7 on 2023-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0007_biometricmetadataforscene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='task',
            field=models.ManyToManyField(null=True, related_name='scenes', through='biosignalsindex.SceneInTaskMetadata', to='biosignalsindex.task'),
        ),
    ]
