# Generated by Django 4.1.7 on 2023-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0007_alter_participantmaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_superepisode',
            field=models.BooleanField(default=True),
        ),
    ]
