# Generated by Django 4.1.7 on 2023-05-02 18:31

from django.db import migrations

def change_names(apps, schema_editor):
    axes = [
        {
            "thematic": "Περιβάλλον",
            "axes": {
                1: "Negative feelings about the city and its environment",
                2: "Positive feelings about the urban environment of the city",
                3: "The citizen towards the city",
                4: "The city towards the citizen",
                5: "The negative presence of industry in the city",
                6: "The positive presence of industry in the city",
                7: "The citizen as an individual",
                8: "The citizen as a collective"
            }
        },
        {
            "thematic": "Εργασία",
            "axes": {
                1: "Working conditions",
                2: "Safety and protection of workers",
                3: "Individual responsibility",
                4: "Accountability of responsible entities",
                5: "Conflict",
                6: "Participation/cooperation",
                7: "Negative emotions",
                8: "Positive emotions"
            }
        },
        {
            "thematic": "Μεταναστευτικό",
            "axes": {
                1: "Feelings of the foreigner",
                2: "Foreigner's attitude towards the local",
                3: "Foreigner's relationship to their place of origin",
                4: "Foreigner's needs/expectations",
                5: "Local/native's feelings towards the foreigner",
                6: "Local/native's attitude towards the foreigner",
                7: "Relationship between local/native and place of origin",
                8: "Local/native's needs/expectations"
            }
        }
    ]

    ThematicUnit = apps.get_model('biosignalsindex', 'ThematicUnit')
    qs = ThematicUnit.objects.all()
    for unit in axes:
        tu = qs.get(name=unit["thematic"])
        for axis in tu.axes.all():
            axis.title = unit["axes"][axis.axis_id_in_thematic]
            axis.save()


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0009_change_axis_colors'),
    ]

    operations = [
        migrations.RunPython(change_names),
    ]
