# Generated by Django 4.2.4 on 2025-10-14 14:06

from django.db import migrations

def populate_city_data(apps, schema_editor):
    City = apps.get_model('biosignalsindex', 'City')
    ThematicUnit = apps.get_model('biosignalsindex', 'ThematicUnit')
    Axis = apps.get_model('biosignalsindex', 'Axis')
    SociodramaSession = apps.get_model('biosignalsindex', 'SociodramaSession')

    # Create city
    eleusis, _ = City.objects.get_or_create(name="Eleusis")

    # Update existing records
    ThematicUnit.objects.update(city=eleusis)
    Axis.objects.update(city=eleusis)
    SociodramaSession.objects.update(city=eleusis)

def reverse_city_data(apps, schema_editor):
    City = apps.get_model('biosignalsindex', 'City')
    City.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0009_add_city_model'),
    ]

    operations = [
        migrations.RunPython(populate_city_data, reverse_city_data),
    ]
