# Generated by Django 4.2.4 on 2025-10-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0010_populate_city_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='biosignalsindex.city'),
        ),
        migrations.AlterField(
            model_name='sociodramasession',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='biosignalsindex.city'),
        ),
        migrations.AlterField(
            model_name='thematicunit',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematics', to='biosignalsindex.city'),
        ),
        migrations.AddConstraint(
            model_name='thematicunit',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_city_thematic'),
        ),
    ]
