# Generated by Django 4.2.4 on 2025-10-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0011_add_city_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sociodramasession',
            name='unique_thematic_session',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_section_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='biosignalsindex.section'),
        ),
        migrations.AddConstraint(
            model_name='sociodramasession',
            constraint=models.UniqueConstraint(fields=('city', 'thematic', 'session_id_in_thematic'), name='unique_thematic_session_per_city'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('section', 'task_no_in_section'), name='unique_section_task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('session', 'task_no_in_section'), name='unique_session_task'),
        ),
    ]
