# Generated by Django 4.2.4 on 2025-10-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0012_remove_sociodramasession_unique_thematic_session_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='axis',
        #     name='unique_thematic_axis',
        # ),
        migrations.AddConstraint(
            model_name='axis',
            constraint=models.UniqueConstraint(fields=('city', 'thematic', 'axis_id_in_thematic'), name='unique_thematic_axis_per_city'),
        ),
    ]
