# Generated by Django 4.2.4 on 2025-10-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0013_remove_axis_unique_thematic_axis_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='axis',
            name='unique_thematic_axis',
        ),
    ]
