# Generated by Django 4.2.4 on 2025-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosignalsindex', '0014_remove_old_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thematicunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
